config/routes.rb
Flatwhite::Application.routes.draw do
  devise_for :users
  resources :comments

  resources :coffee_attempts

   root 'home#index'

  

end

app/models/coffee_attempt.rb
class CoffeeAttempt < ActiveRecord::Base

	has_many :comments
	belongs_to :user
	
	mount_uploader :picture, PhotoUploader

	validates_presence_of :name, :description, :picture, :user_id




  	def self.latest
		CoffeeAttempt.last
  	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :coffee_attempt
	belongs_to :user

	validates_presence_of :body
  	
end

app/models/user.rb
class User < ActiveRecord::Base

	validates_presence_of :user_name
	validates_uniqueness_of :user_name
	has_many :coffee_attempts
	has_many :comments
	# Include default devise modules. Others available are:
	# :token_authenticatable, :confirmable,
	# :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?



  protected

  def configure_permitted_parameters
    #devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:user_name, :email) }
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:user_name, :email, :password, :password_confirmation) }
  end



  def authorize_user!
    if user_signed_in?
      return
    else
      flash[:notice] = 'Sorry, you need to sign in first'
      redirect_to new_user_session_path
    end
  end

end

app/controllers/coffee_attempts_controller.rb
class CoffeeAttemptsController < ApplicationController
  before_action :set_coffee_attempt, only: [:show, :edit, :update, :destroy]
  before_filter :authorize_user!, :except => [:index, :show]


  # GET /coffee_attempts
  # GET /coffee_attempts.json
  def index
    @coffee_attempts = CoffeeAttempt.all
  end

  # GET /coffee_attempts/1
  # GET /coffee_attempts/1.json
  def show
  end

  # GET /coffee_attempts/new
  def new
    @coffee_attempt = CoffeeAttempt.new
  end

  # GET /coffee_attempts/1/edit
  def edit
  end

  # POST /coffee_attempts
  # POST /coffee_attempts.json
  def create
    @coffee_attempt = CoffeeAttempt.new(coffee_attempt_params)
    
    respond_to do |format|
      if @coffee_attempt.save
        format.html { redirect_to @coffee_attempt, notice: 'Coffee attempt was successfully created.' }
        format.json { render action: 'show', status: :created, location: @coffee_attempt }
      else
        format.html { render action: 'new' }
        format.json { render json: @coffee_attempt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coffee_attempts/1
  # PATCH/PUT /coffee_attempts/1.json
  def update

    respond_to do |format|
      if @coffee_attempt.update(coffee_attempt_params)

        format.html { redirect_to @coffee_attempt, notice: 'Coffee attempt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @coffee_attempt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coffee_attempts/1
  # DELETE /coffee_attempts/1.json
  def destroy
    @coffee_attempt.destroy
    respond_to do |format|
      format.html { redirect_to coffee_attempts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coffee_attempt
      @coffee_attempt = CoffeeAttempt.find(params[:id])
      @comment = @coffee_attempt.comments.build
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coffee_attempt_params
      params.require(:coffee_attempt).permit(:name, :description, :picture).merge(user: current_user)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to :back, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @coffee_attempt }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])


    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :coffee_attempt_id).merge(user: current_user)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


	def index
		@latest_attempt = CoffeeAttempt.latest
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def bootstrapped_alerts(type)
		case type
		when :alert || :error
		"alert-danger"
		when :notice
		"alert-info"
		when :success
		"alert-success"
		else
		type.to_s
		end
	end

end

app/helpers/coffee_attempts_helper.rb
module CoffeeAttemptsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_chromeframe.html.erb
<!--[if lt IE 7]>
  <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->

app/views/application/_flash_messages.html.haml
- flash.each do |type, message|
	%div.alert.fade.in{ "data-alert" => "alert", :class => bootstrapped_alerts(type) }
		%a.close{:href => "#"} ×
		%p
		= message

app/views/application/_footer.html.erb
<footer id="footer">
	<div class="container">
	  <small class="copyright">
	    Flatwhite Fortunes, Copyright &copy; <%= Date.today.year %>
	  </small>
	</div>
</footer>

app/views/application/_head.html.erb
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title><%= content_for?(:title) ? yield(:title) : "Flatwhite Fortunes" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Mmmmm Coffee" %>">
  <meta name="viewport" content="width=device-width , initial-scale=1.0">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "polyfills" %>

  <%= csrf_meta_tag %>
</head>

app/views/application/_header.html.erb
<header id="header" class="navbar navbar-fixed-top bs-docs-nav">
  <div class="container">
    <nav class="navbar-header" role="navigation">
      <div>
        <button type="button" class="navbar-toggle glyphicon glyphicon-align-justify" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">FlatWhite Fortunes</a>
      </div>
    </nav>

    <nav class="collapse navbar-collapse bs-navbar-collapse navbar-ex1-collapse" role="navigation">

      <ul class="nav navbar-nav">
        <li class="active"><a href="/coffee_attempts">View all</a></li>
        <li><%= link_to 'Add your Coffee Attempt', new_coffee_attempt_path %></li>
      </ul>

        <div class="pull-right">
          <div class="navbar-link">
            
                <% if user_signed_in? %>
                    <span class="navbar-link">Hi
                        <%= current_user.user_name %>
                    </span>
                    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
                <% else %>
                    <ul>
                        <li>
                            <%= link_to 'Login', new_user_session_path %>
                        </li>
                            <li><%= link_to 'Sign up', new_user_registration_path %>
                        </li>
                    </ul>

                <% end %>

          

      </div>
    </nav>

  </div>
</header>

app/views/coffee_attempts/_form.html.erb
<%= form_for @coffee_attempt, html: {class: "form form-horizontal"} do |f| %>


  <% if @coffee_attempt.errors.any? %>
    <div id="error_explanation" class="alert alert-notice">
      <h2><%= pluralize(@coffee_attempt.errors.count, "error") %> prohibited this coffee_attempt from being saved:</h2>

      <ul>
      <% @coffee_attempt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class=>"label" %>
    <%= f.text_field :name, :class=>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class=>"label" %>
    <%= f.text_area :description, :class=>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :picture, :class=>"label" %>
    <%= f.file_field :picture, :class=>'form-control' %>
  </div>
  <div class="form-actions">
    <%= f.submit "Submit", :class=> 'btn btn-primary' %>
  </div>
<% end %>

app/views/coffee_attempts/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

<%= link_to 'Show', @coffee_attempt %> |
<%= link_to 'Back', coffee_attempts_path %>

app/views/coffee_attempts/index.html.erb
<p>Submit your coffee art</p>

<div class="row">
  <% @coffee_attempts.each do |coffee_attempt| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag(coffee_attempt.picture_url, :width => 200)), coffee_attempt if coffee_attempt.picture.present? %>
        <div class="caption">
          <h3><%= link_to coffee_attempt.name, coffee_attempt %></h3>
          <p><%= coffee_attempt.description %></p>
          <p class="small-font">
            <%= coffee_attempt.user.user_name %>
          </p>
          <% if coffee_attempt.user == current_user %>
            <%= link_to 'Edit', edit_coffee_attempt_path(coffee_attempt) %>
            <%= link_to 'Delete', coffee_attempt, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/coffee_attempts/new.html.erb
<h1>Submit</h1>

<%= render 'form' %>

<%= link_to 'Back', coffee_attempts_path %>

app/views/coffee_attempts/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
<%= @coffee_attempt.name %>
</h2>
<p>
  <strong>Description</strong>
  <%= @coffee_attempt.description %>
</p>

<%= image_tag(@coffee_attempt.picture_url) if @coffee_attempt.picture.present? %>

<h3>Comments</h3>
<% @coffee_attempt.comments.each do |comment| %>
  <div>
    <p><%= comment.body %></p>
  </div>
<% end %>

<%= render 'comments/form', collection: @coffee_attempt.comments %>

<%= link_to 'Edit', edit_coffee_attempt_path(@coffee_attempt) %> |
<%= link_to 'Back', coffee_attempts_path %>

app/views/comments/_form.html.erb
<%= form_for(@comment , html: {class: "form form-horizontal"}) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation" class="alert alert-notice">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label 'Comment' %>
    <%= f.text_area :body, :class=>'form-control' %>
    <%= f.hidden_field :coffee_attempt_id %>
  </div>
  <div class="form-actions">
    <%= f.submit "submit", :class=> 'btn btn-default' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Comment</th>
      <th>Coffee Photo</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <%#= comment.user_id.user_name %>
        <%= comment.user.user_name %>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>

</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/index.html.haml
.latest-view.col-md-4.col-md-offset-4

	%p
		=link_to 'Add yours', new_coffee_attempt_path

	-if @latest_attempt.present?
	
		%h2 Latest

		.thumbnail
			= link_to (image_tag(@latest_attempt.picture_url, :width => 300)), @latest_attempt if @latest_attempt.picture.present?


		%h3=@latest_attempt.name
		%p= @latest_attempt.description
		%p.small-font 
			Posted by:
			= @latest_attempt.user.user_name


%h4 Inspiration
<iframe src="//player.vimeo.com/video/66343904?title=0&amp;byline=0&amp;portrait=0" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> <p><a href="http://vimeo.com/66343904">VCR StreetSmarts #14: Latte Art</a> from <a href="http://vimeo.com/vervecoffee">Verve Coffee Roasters</a> on <a href="https://vimeo.com">Vimeo</a>.</p>

app/views/layouts/application.html.haml
!!!
= html_tag :class => "no-js"
= render "head"
%body{:class => controller.controller_name}
  = render "chromeframe"
  = render "header"
  

  .container
    =render :partial => "application/flash_messages", :locals => {:flash => flash}

    %h1 FlatWhite Fortunes
    = yield
  = render "footer"
  = render "javascripts"